import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import Boolean, Computed, DateTime, ForeignKey, Text, false, func
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base

EMBEDDING_DIM = 8


class Item(Base):
    """A short text with an embedding: exists to prove that production Postgres has
    pgvector (HNSW, cosine) and the `romanian` text search configuration.

    `search` is generated by Postgres, so it can never go stale; the app never
    writes it.
    """

    __tablename__ = "items"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    org_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("orgs.id"), nullable=False, index=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)
    search: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('romanian', title || ' ' || body)", persisted=True),
    )
    # Added by migration 0002, so every deploy has more than one migration to run.
    pinned: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
